object Secret {
    const val ENABLE_API_LOG = "ENABLE_API_LOG"
    const val ENABLE_TRUSTED_BASE_URL = "ENABLE_TRUSTED_BASE_URL"
    const val ENABLE_TRUST_MANAGER = "ENABLE_TRUST_MANAGER"
    const val ENABLE_UNSECURE_HTTP_PROTOCOL = "ENABLE_UNSECURE_HTTP_PROTOCOL"
}